## Ways to generate random numbers with numpy

In [1]:
import numpy as np

In [2]:
# Generate 2x3 grid of random numbers between [0, 100)
# using "discrete uniform" distribution
np.random.randint(0, 100, (2,3))

array([[53, 53, 48],
       [68, 29, 59]])

In [3]:
# Generating a random number from the normal distribution 
# with mean 0.0 and stddev of 1.
np.random.normal()

1.191834434069972

In [4]:
# Generating a random number from the normal distribution 
# with mean 10.0 and stddev of 1.
np.random.normal(loc=10, scale=1)

10.086893359924652

In [5]:
# Generating a 2x3 grid of random numbers from the normal distribution 
# with mean 10.0 and stddev of 1.
np.random.normal(loc=10, scale=1, size=(2,3))

array([[ 11.70035726,  10.11348258,   9.88327571],
       [ 12.09464881,   9.5972517 ,   8.55275313]])

In [6]:
# Generating a random number from the uniform distribution 
# with [low, high).
np.random.uniform(low=0, high=10)

0.13515888530870157

In [7]:
# Generating a 2x3 grid of random numbers from the uniform distribution 
# with [low, high).
np.random.uniform(low=0, high=10, size=(2, 3))

array([[ 2.5021177 ,  1.80565781,  5.25225599],
       [ 3.93104197,  0.93518092,  9.33351674]])

In [10]:
# Generate a 2x3 grid of random numbers from normal distribution
np.random.randn(2, 3)

array([[ 0.51554249,  0.62749352,  0.91704761],
       [ 1.30093222, -0.17214047, -0.07824602]])