In [1]:
# Generate some random data

import numpy as np

heights_mt = np.round(np.random.normal(1.75, 0.25, 500), 2)

weights_kg = np.round(np.random.normal(70, 5, 500), 2)

players = np.column_stack((heights_mt, weights_kg))

In [2]:
# Inspect
print(type(heights_mt))
print(heights_mt.shape)
print(weights_kg.shape)
print(players.shape)

<class 'numpy.ndarray'>
(500,)
(500,)
(500, 2)


In [3]:
# Fetch elements

print(players[0])

[  1.46  79.  ]


In [4]:
players[0,0]

1.46

In [5]:
players[0:5, 0]

array([ 1.46,  1.79,  1.5 ,  1.94,  1.55])

In [6]:
# Mean, Median, StdDev

print(np.mean(players[:, 0]))
print(np.mean(players[:, 1]))
print(np.median(players[:, 0]))
print(np.median(players[:, 1]))
print(np.std(players[:, 0]))
print(np.std(players[:, 1]))

1.75746
70.49996
1.75
70.58
0.254569731901
5.10008313642


In [7]:
# Select based on criteria

# Players who are more than 2.25 mts tall
players[players[:, 0] > 2.25]

array([[  2.37,  68.12],
       [  2.27,  70.03],
       [  2.26,  68.76],
       [  2.38,  75.68],
       [  2.33,  66.49],
       [  2.42,  71.53],
       [  2.29,  68.96],
       [  2.37,  66.13],
       [  2.6 ,  75.37],
       [  2.37,  74.48],
       [  2.27,  73.63],
       [  2.28,  66.88],
       [  2.26,  81.27],
       [  2.29,  66.01],
       [  2.39,  70.75],
       [  2.26,  68.42],
       [  2.27,  66.61],
       [  2.27,  68.51]])

In [8]:
# Players who are more than 80 kg in weight
players[players[:, 1] > 80]

array([[  1.61,  80.56],
       [  2.05,  81.11],
       [  1.89,  80.7 ],
       [  1.52,  81.4 ],
       [  2.1 ,  82.22],
       [  1.81,  81.38],
       [  1.64,  83.8 ],
       [  2.17,  82.  ],
       [  2.26,  81.27],
       [  1.65,  90.25],
       [  1.98,  82.4 ]])

In [16]:
option_a = np.round(np.random.normal(1.75, 0.25, 10), 2)
option_b = np.round(np.random.normal(1.75, 0.25, 10), 2)
print(option_a)
print(option_b)

[ 1.97  1.44  2.17  1.78  1.3   1.51  1.93  2.17  1.71  1.52]
[ 1.73  1.59  1.65  1.86  1.49  1.5   2.17  1.47  1.37  1.42]


In [17]:
option_a > 1.7

array([ True, False,  True,  True, False, False,  True,  True,  True, False], dtype=bool)

In [18]:
option_b > 1.7

array([ True, False, False,  True, False, False,  True, False, False, False], dtype=bool)

In [19]:
np.logical_and(option_a > 1.7, option_b > 1.7)

array([ True, False, False,  True, False, False,  True, False, False, False], dtype=bool)

In [20]:
np.logical_or(option_a > 1.7, option_b > 1.7)

array([ True, False,  True,  True, False, False,  True,  True,  True, False], dtype=bool)

In [21]:
new_np_array = np.array([option_a, option_b])

In [23]:
new_np_array

array([[ 1.97,  1.44,  2.17,  1.78,  1.3 ,  1.51,  1.93,  2.17,  1.71,
         1.52],
       [ 1.73,  1.59,  1.65,  1.86,  1.49,  1.5 ,  2.17,  1.47,  1.37,
         1.42]])

In [24]:
for item in np.nditer(new_np_array):
    print(item)

1.97
1.44
2.17
1.78
1.3
1.51
1.93
2.17
1.71
1.52
1.73
1.59
1.65
1.86
1.49
1.5
2.17
1.47
1.37
1.42
